import { expect, test, type Page } from '@playwright/test';
import { randomBytes } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';

const app = process.env.STARTER_TEST_APP!;
const mailLog = path.join(app, 'storage/logs/laravel.log');
const readMail = () => readFileSync(mailLog, 'utf8');

async function mailedLink(
    offset: number,
    email: string,
    pathname: string,
    origin: string,
): Promise<string> {
    let link: URL | undefined;
    await expect
        .poll(() => {
            // Laravel's log transport already decodes quoted-printable bodies.
            // Read only mail generated by this synthetic account's latest action.
            const message = readMail().slice(offset);
            if (!message.includes(email)) return false;
            for (const match of message.matchAll(/href="([^"]+)"/g)) {
                const url = new URL(match[1].replaceAll('&amp;', '&'));
                if (url.pathname.startsWith(pathname)) link = url;
            }
            return Boolean(link);
        })
        .toBe(true);
    expect(link!.origin).toBe(origin);
    return link!.toString();
}

async function submitLogin(page: Page, email: string, password: string) {
    await page.goto('/login');
    await page.getByLabel('Email address', { exact: true }).fill(email);
    await page.getByLabel('Password', { exact: true }).fill(password);
    await page.locator('[data-test="login-button"]').click();
}

test('account creation, verification, password recovery, and deletion work', async ({
    page,
}, info) => {
    test.setTimeout(90_000);
    const features: { registration: boolean; verification: boolean } =
        JSON.parse(
            readFileSync(
                path.join(
                    app,
                    'storage/framework/testing/browser-features.json',
                ),
                'utf8',
            ),
        );
    const email = `account-${info.project.name}@example.test`;
    const initialPassword = features.registration
        ? `Account-${randomBytes(18).toString('base64url')}9!`
        : 'Browser-test-password-9!';
    const newPassword = `Reset-${randomBytes(18).toString('base64url')}9!`;
    const errors: string[] = [];
    page.on('pageerror', (error) => errors.push(error.message));
    page.on('console', (message) => {
        if (
            message.type() === 'error' ||
            /hydration|hydrating|did not match|server rendered/i.test(
                message.text(),
            )
        )
            errors.push(message.text());
    });
    page.on('response', (response) => {
        if (response.status() >= 500)
            errors.push(`${response.status()} ${response.url()}`);
    });

    let verificationMailOffset = readMail().length;
    if (features.registration) {
        await page.goto('/register');
        await page
            .getByLabel('Name', { exact: true })
            .fill('Account Lifecycle');
        await page.getByLabel('Email address', { exact: true }).fill(email);
        await page
            .getByLabel('Password', { exact: true })
            .fill(initialPassword);
        await page
            .getByLabel('Confirm password', { exact: true })
            .fill(initialPassword);
        await page.locator('[data-test="register-user-button"]').click();
    } else {
        // prepare.php provisions an unverified account only when signup is absent.
        await submitLogin(page, email, initialPassword);
    }

    if (features.verification) {
        await expect(page).toHaveURL(/\/email\/verify$/);
        await expect(
            page.getByRole('heading', {
                name: 'Email verification',
                exact: true,
            }),
        ).toBeVisible();
        if (!features.registration) {
            verificationMailOffset = readMail().length;
            await page
                .getByRole('button', { name: 'Resend verification email' })
                .click();
            await expect(
                page.getByText(
                    'A new verification link has been sent to your email address.',
                ),
            ).toBeVisible();
        }
        const verificationUrl = await mailedLink(
            verificationMailOffset,
            email,
            '/email/verify/',
            new URL(page.url()).origin,
        );
        await page.goto(verificationUrl);
        await expect(page).toHaveURL(/\/dashboard(?:\?verified=1)?$/);
        // A fresh request must retain verified access, not just the redirect.
        await page.reload();
    }
    await expect(page).toHaveURL(/\/dashboard(?:\?verified=1)?$/);
    await page.locator('[data-test="sidebar-menu-button"]').click();
    await page.locator('[data-test="logout-button"]').click();
    await expect(page).not.toHaveURL(/\/dashboard/);

    await page.goto('/forgot-password');
    const resetMailOffset = readMail().length;
    await page.getByLabel('Email address', { exact: true }).fill(email);
    await page
        .locator('[data-test="email-password-reset-link-button"]')
        .click();
    await expect(
        page.getByText(
            'If an account exists with that email address, you’ll receive a password reset link shortly.',
        ),
    ).toBeVisible();
    const resetUrl = await mailedLink(
        resetMailOffset,
        email,
        '/reset-password/',
        new URL(page.url()).origin,
    );
    expect(new URL(resetUrl).searchParams.get('email')).toBe(email);
    await page.goto(resetUrl);
    await expect(page.getByLabel('Email address', { exact: true })).toHaveValue(
        email,
    );
    await page.getByLabel('New password', { exact: true }).fill(newPassword);
    await page
        .getByLabel('Confirm password', { exact: true })
        .fill(newPassword);
    await page.locator('[data-test="reset-password-button"]').click();
    await expect(page).toHaveURL(/\/login$/);
    await submitLogin(page, email, newPassword);
    await expect(page).toHaveURL(/\/dashboard$/);

    await page.goto('/settings/profile');
    await page.locator('[data-test="delete-user-button"]').click();
    const deletion = page.getByRole('dialog', { name: 'Delete account?' });
    await expect(deletion).toBeVisible();
    await deletion
        .getByLabel('Current password', { exact: true })
        .fill(newPassword);
    await deletion
        .getByRole('button', { name: 'Delete account', exact: true })
        .click();
    await expect(page).toHaveURL(new URL('/', page.url()).toString());
    await submitLogin(page, email, newPassword);
    await expect(
        page.getByText('These credentials do not match our records.', {
            exact: true,
        }),
    ).toBeVisible();
    await page.goto('/dashboard');
    await expect(page).toHaveURL(/\/login$/);

    expect(errors).toEqual([]);
    expect(
        readMail().match(/^\[.*\.(?:ERROR|CRITICAL|ALERT|EMERGENCY):.*$/gm) ||
            [],
    ).toEqual([]);
});
